"""Tiny in-process TTL + LRU cache (grounded answers, TTS audio).

Deliberately ephemeral: it lives in the worker process and dies with it, so a
deploy (container recreate) always starts cold and can never serve answers
generated by old code. No external cache/DB — the proxy stays stateless.
"""

import time
from collections import OrderedDict
from typing import Any, Hashable, Optional


class TTLCache:
    """LRU cache whose entries expire ``ttl_s`` seconds after insertion.

    ``max_size <= 0`` or ``ttl_s <= 0`` disables the cache entirely (every
    ``get`` misses, ``put`` is a no-op). Not thread-safe; fine under a single
    asyncio event loop.
    """

    def __init__(self, max_size: int, ttl_s: float):
        self.max_size = max_size
        self.ttl_s = ttl_s
        self._data: "OrderedDict[Hashable, tuple[float, Any]]" = OrderedDict()

    @property
    def enabled(self) -> bool:
        return self.max_size > 0 and self.ttl_s > 0

    def get(self, key: Hashable) -> Optional[Any]:
        if not self.enabled:
            return None
        item = self._data.get(key)
        if item is None:
            return None
        expires, value = item
        if time.monotonic() >= expires:
            del self._data[key]
            return None
        self._data.move_to_end(key)
        return value

    def put(self, key: Hashable, value: Any) -> None:
        if not self.enabled:
            return
        self._data[key] = (time.monotonic() + self.ttl_s, value)
        self._data.move_to_end(key)
        while len(self._data) > self.max_size:
            self._data.popitem(last=False)
